export const state = {
  productDialog: false,
  isEditingSale: false,
  sales: [],
  headers: [
    { text: "Valor total", value: "total_value" },
    { text: "Cliente", value: "client.full_name" },
    { text: "Tipo de venda", value: "actions" },
    { text: "Método de pagamento", value: "payment_method.name" },
    { text: "Vendedor", value: "user.user_name" },
    { text: "Ações", value: "actions" },
  ],
  productsByManufacturers: [],
  salesTypes: ["Atacado", "Varejo"],
  selectedManufacturerFromFilter: "",
  salesFormFields: {
    selectedPaymentMethod: "",
    selectedClient: "",
    saleDate: "",
    selectedSalesType: null,
    products: [],
  },
  productFormFields: {
    id: null,
    quantity: 1,
    serialNumbers: [],
    unityValue: 0,
    selectedProduct: null,
  },
  salesErrorMessages: {
    serialNumber: "",
    serialNumbers: [""],
    quantity: "",
    unityValue: "",
    selectedProduct: "",
    selectedPaymentMethod: "",
    selectedClient: "",
    saleDate: "",
    selectedSalesType: "",
  },
  serialNumbersDialog: false,
  showContent: true,
};
